import type { InferGetServerSidePropsType, NextPage } from 'next'
import Head from 'next/head'
import FrontPage from '../component/FrontPage'


import HomeHeader from '../component/HomeHeader'

import { API_URL } from '../config'
import FullLayout from '../hoc/FullLayout'
// import Image from 'next/image'

import styles from '../styles/Home.module.css'
import { cycleType } from '../types/alltypes'

const Home=({data}:InferGetServerSidePropsType<typeof getServerSideProps>) => {
  // console.log(data);
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Cycle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeHeader />
      <main className={styles.main}>
       <FrontPage />
      </main>

     
    </div>
  )
}

export default Home

Home.getLayout = function getLayout(page:typeof Home){
  return <FullLayout>{page}</FullLayout>
}

export const getServerSideProps =async(context: any)=>{
  const res = await fetch(`${API_URL}/shop/cycle/`,{
      method:"GET"
  })
  const data:cycleType[] = await res.json()
  // console.log(data);
 
  
  if(data){
      return {
          props:{data}
      }
  }else{
      return {
          props:{}
      }
  }
  

}
